apiVersion: apps/v1
kind: Deployment
metadata:
  name: ascraper
  namespace: selfservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ascraper
  template:
    metadata:
      labels:
        app: ascraper
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
    spec:
      serviceAccount: ascraper-sa
      containers:
        - name: app
          image: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/selfservice/ascraper:{{BUILD_NUMBER}}
          ports:
            - name: metrics
              containerPort: 8888
          resources:
            requests:
              memory: "20Mi"
              cpu: "50m"
            limits:
              memory: "100Mi"
              cpu: "100m"

