apiVersion: v1
kind: ServiceAccount
metadata:
  name: ascraper-sa
  namespace: selfservice
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ascraper-services-read
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ascraper-services-read
subjects:
  - kind: ServiceAccount
    name: k8s-janitor-sa
    namespace: selfservice
roleRef:
  kind: ClusterRole
  name: ascraper-services-read
  apiGroup: rbac.authorization.k8s.io
